version: "3"
services:
  app:
    build: .
    ports:
      - "${PORT:-3000}:3000"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env.${NODE_ENV:-dev}
    depends_on:
      mongo:
        condition: service_healthy

  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
  
volumes:
  mongodb_data: